sudo: required

services:
  - docker

before_install:
  - docker build -t ${TRAVIS_REPO_SLUG} .

script:
  - docker run -i -t --rm ${TRAVIS_REPO_SLUG}

before_deploy:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

deploy:
  - provider: script
    script: docker push ${TRAVIS_REPO_SLUG}
